name: VibeBar
options:
  minimumXcodeGenVersion: 2.44.0
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: "14.0"
packages:
  SweetCookieKit:
    url: https://github.com/steipete/SweetCookieKit.git
    from: 0.4.0
targets:
  VibeBarUI:
    type: framework
    platform: macOS
    sources:
      - path: Sources/VibeBarUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibebar.ui
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: YES
  VibeBar:
    type: application
    platform: macOS
    sources:
      - path: Sources/VibeBar
      - path: Resources/Assets.xcassets
        buildPhase: resources
    info:
      path: Config/Info.plist
    dependencies:
      - target: VibeBarUI
      - package: SweetCookieKit
        product: SweetCookieKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibebar.app
        PRODUCT_NAME: VibeBar
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_HARDENED_RUNTIME: NO
      configs:
        Debug:
          ENABLE_DEBUG_DYLIB: YES
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO
        Release:
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGNING_REQUIRED: NO
schemes:
  VibeBar:
    build:
      targets:
        VibeBar: all
    run:
      config: Debug
  VibeBarUI:
    build:
      targets:
        VibeBarUI: all
